version: "3.9"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
volumes:
  data:
